# Generated by Django 5.2.5 on 2025-08-26 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code dossier')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('EA', 'En Attente'), ('EC', 'En Cours'), ('TR', 'Terminé'), ('RJ', 'Rejeté')], default='EA', max_length=2, verbose_name='Statut')),
                ('date_limite', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
            },
        ),
    ]
