# Generated by Django 5.2.5 on 2025-08-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='certificat_ce',
            field=models.BooleanField(default=False, verbose_name='Certificat CE'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_bv',
            field=models.DateField(blank=True, null=True, verbose_name='Date BV'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_depot',
            field=models.DateField(blank=True, null=True, verbose_name='Date de dépôt'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_fin_evaluation',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin évaluation'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_fin_verification',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin vérification'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_notification',
            field=models.DateField(blank=True, null=True, verbose_name='Date notification'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_reception',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='denomination_commerciale',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dénomination Commerciale'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='evaluateur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Évaluateur'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='fabricant',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fabricant'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='numero_bv',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro BV'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='numero_notification',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro notification'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='pays_origine',
            field=models.CharField(blank=True, max_length=50, verbose_name="Pays d'Origine"),
        ),
        migrations.AddField(
            model_name='dossier',
            name='reserves',
            field=models.TextField(blank=True, verbose_name='Réserves'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='type_demande',
            field=models.CharField(blank=True, max_length=50, verbose_name='Type de demande'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='verificateur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vérificateur'),
        ),
    ]
