# Generated by Django 5.2.5 on 2025-08-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_dossier_certificat_ce_dossier_date_bv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code dossier'),
        ),
    ]
